"""
Purpose: Define canonical artifact and export-record persistence models.
Scope: Versioned released artifacts with idempotency protection, export-run
lifecycle tracking, and manifest lineage for evidence packs, report outputs,
audit trails, and QuickBooks export files.
Dependencies: SQLAlchemy ORM primitives, PostgreSQL JSONB support, shared
DB base helpers, and canonical enums from services.common.enums.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from services.common.enums import ArtifactType
from services.common.types import JsonObject
from services.db.base import Base, TimestampedModel, UUIDPrimaryKeyMixin, build_text_choice_check
from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ExportStatus(StrEnum):
    """Enumerate the lifecycle states of an export run."""

    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELED = "canceled"


_ARTIFACT_TYPES = tuple(t.value for t in ArtifactType)
_EXPORT_STATUSES = tuple(s.value for s in ExportStatus)
_EXPORT_DELIVERY_CHANNELS = (
    "secure_email",
    "management_portal",
    "board_pack",
    "file_share",
)


# ---------------------------------------------------------------------------
# Artifact
# ---------------------------------------------------------------------------

class Artifact(Base, UUIDPrimaryKeyMixin, TimestampedModel):
    """Persist one released artifact snapshot linked to a close run version.

    An artifact represents an immutable generated output — such as a report
    pack, evidence pack, audit trail, or QuickBooks export file — that is
    tied to a specific close run version and protected by an idempotency key
    so duplicate export actions resolve to the same row.
    """

    __tablename__ = "artifacts"
    __table_args__ = (
        build_text_choice_check(
            column_name="artifact_type",
            values=_ARTIFACT_TYPES,
            constraint_name="artifact_type_valid",
        ),
        CheckConstraint("version_no >= 1", name="version_no_positive"),
        # Idempotency guard: one artifact per type + idempotency key.
        UniqueConstraint(
            "artifact_type",
            "idempotency_key",
            name="uq_artifacts_type_idempotency",
        ),
        Index("ix_artifacts_close_run_id", "close_run_id"),
        Index("ix_artifacts_artifact_type", "artifact_type"),
        Index("ix_artifacts_idempotency_key", "idempotency_key"),
        Index("ix_artifacts_close_run_version", "close_run_id", "version_no"),
    )

    close_run_id: Mapped[UUID] = mapped_column(
        ForeignKey("close_runs.id"),
        nullable=False,
        comment="Close run this artifact snapshot belongs to.",
    )
    report_run_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("report_runs.id"),
        nullable=True,
        comment="Parent report run when this artifact was generated by a report run.",
    )
    artifact_type: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Released artifact category: report_excel, evidence_pack, audit_trail, etc.",
    )
    storage_key: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Object-storage key where the artifact payload lives.",
    )
    mime_type: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="MIME type of the stored artifact payload.",
    )
    checksum: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="SHA-256 checksum of the stored artifact payload.",
    )
    idempotency_key: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Stable idempotency key that guards against duplicate release.",
    )
    version_no: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Close-run version number this artifact belongs to.",
    )
    released_at: Mapped[datetime | None] = mapped_column(
        nullable=True,
        comment="UTC timestamp when the artifact was officially released.",
    )
    artifact_metadata: Mapped[JsonObject] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
        comment="Additional artifact-level metadata for lineage and diagnostics.",
    )


# ---------------------------------------------------------------------------
# Export Run
# ---------------------------------------------------------------------------

class ExportRun(Base, UUIDPrimaryKeyMixin, TimestampedModel):
    """Persist one export execution for a close run.

    An export run captures the intent to package and release artifacts for a
    close run version.  It tracks the lifecycle from pending through completed
    or failed, and records the idempotency key so duplicate export clicks
    return the existing export instead of creating a duplicate.
    """

    __tablename__ = "export_runs"
    __table_args__ = (
        build_text_choice_check(
            column_name="status",
            values=_EXPORT_STATUSES,
            constraint_name="export_status_valid",
        ),
        CheckConstraint("version_no >= 1", name="export_version_no_positive"),
        UniqueConstraint(
            "close_run_id",
            "idempotency_key",
            name="uq_export_runs_close_run_idempotency",
        ),
        Index("ix_export_runs_close_run_id", "close_run_id"),
        Index("ix_export_runs_status", "status"),
        Index("ix_export_runs_idempotency_key", "idempotency_key"),
    )

    close_run_id: Mapped[UUID] = mapped_column(
        ForeignKey("close_runs.id"),
        nullable=False,
        comment="Close run this export was generated for.",
    )
    version_no: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Close-run version number this export belongs to.",
    )
    idempotency_key: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Deterministic idempotency key for this export action.",
    )
    status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Current export lifecycle status.",
    )
    failure_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Structured failure description when status is 'failed'.",
    )
    artifact_manifest: Mapped[JsonObject] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
        comment=(
            "Array of artifact storage keys and metadata included in this export."
        ),
    )
    evidence_pack_key: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Idempotency key of the evidence pack included in this export, if any.",
    )
    triggered_by_user_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("users.id"),
        nullable=True,
        comment="User who triggered this export run.",
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        nullable=True,
        comment="UTC timestamp when the export reached a terminal state.",
    )


class ExportDistribution(Base, UUIDPrimaryKeyMixin, TimestampedModel):
    """Persist one management-delivery event for a completed export run."""

    __tablename__ = "export_distributions"
    __table_args__ = (
        build_text_choice_check(
            column_name="delivery_channel",
            values=_EXPORT_DELIVERY_CHANNELS,
            constraint_name="export_distribution_delivery_channel_valid",
        ),
        Index("ix_export_distributions_export_run_id", "export_run_id"),
        Index("ix_export_distributions_distributed_at", "distributed_at"),
        Index("ix_export_distributions_close_run_id", "close_run_id"),
        UniqueConstraint(
            "export_run_id",
            "recipient_email",
            "delivery_channel",
            "distributed_at",
            name="uq_export_distributions_export_recipient_channel_time",
        ),
    )

    export_run_id: Mapped[UUID] = mapped_column(
        ForeignKey("export_runs.id", ondelete="CASCADE"),
        nullable=False,
        comment="Completed export package this delivery record belongs to.",
    )
    entity_id: Mapped[UUID] = mapped_column(
        ForeignKey("entities.id"),
        nullable=False,
        comment="Entity workspace that owns the distribution event.",
    )
    close_run_id: Mapped[UUID] = mapped_column(
        ForeignKey("close_runs.id"),
        nullable=False,
        comment="Close run that the export delivery belongs to.",
    )
    version_no: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Close-run version number that was distributed.",
    )
    recipient_name: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Stakeholder display name for the recorded release.",
    )
    recipient_email: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Stakeholder delivery email recorded for the release.",
    )
    recipient_role: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Optional stakeholder role such as CFO or Finance Manager.",
    )
    delivery_channel: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Canonical delivery channel used for the stakeholder release.",
    )
    note: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional operator note recorded with the delivery event.",
    )
    distributed_by_user_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("users.id"),
        nullable=True,
        comment="User who recorded the distribution event.",
    )
    distributed_at: Mapped[datetime] = mapped_column(
        nullable=False,
        comment="UTC timestamp when the package was released to the stakeholder.",
    )


__all__ = [
    "Artifact",
    "ExportDistribution",
    "ExportRun",
    "ExportStatus",
]
